-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 01:41:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema propertyRental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema propertyRental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `propertyRental` DEFAULT CHARACTER SET utf8 ;
USE `propertyRental` ;

-- -----------------------------------------------------
-- Table `propertyRental`.`host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`host` (
  `hostID` DECIMAL(8,0) NOT NULL,
  `userName` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `description` VARCHAR(90) NULL,
  `joinDate` DATE NOT NULL,
  `email` VARCHAR(25) NULL,
  `phoneNumber` VARCHAR(20) NULL,
  `earnings` DECIMAL(10,2) ZEROFILL NOT NULL,
  PRIMARY KEY (`hostID`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO `propertyRental`.`host` (`hostID`, `userName`, `password`, `firstName`, `lastName`, `description`, `joinDate`, `email`, `phoneNumber`, `earnings`) VALUES
(10000001, 'hostUser1', 'pass1234', 'John', 'Doe', 'Experienced host in urban areas', '2023-01-10', 'john.doe@example.com', '1234567890', 000001500.00),
(10000002, 'hostUser2', 'pass5678', 'Jane', 'Smith', 'Specializes in cozy rural stays', '2023-02-15', 'jane.smith@example.com', '0987654321', 000000750.50),
(10000003, 'hostUser3', 'pass9101', 'Alice', 'Johnson', 'Luxury apartment provider', '2023-03-20', 'alice.j@example.com', '5678901234', 000002300.75),
(10000004, 'hostUser4', 'pass1123', 'Bob', 'Brown', 'Friendly and attentive host', '2023-04-05', 'bob.brown@example.com', '6789012345', 000001200.30),
(10000005, 'hostUser5', 'pass3141', 'Charlie', 'Davis', 'Great locations in the city center', '2023-05-10', 'charlie.d@example.com', '7890123456', 000000900.00);

-- -----------------------------------------------------
-- Table `propertyRental`.`propertyListing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`propertyListing` (
  `propertyListingID` DECIMAL(8,0) NOT NULL,
  `hostID` DECIMAL(8,0) NOT NULL,
  `listingName` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NULL,
  `pricePerNight` DECIMAL(10,2) ZEROFILL NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`propertyListingID`),
  INDEX `hostID_idx` (`hostID` ASC) VISIBLE,
  CONSTRAINT `hostID_property_fk`
    FOREIGN KEY (`hostID`)
    REFERENCES `propertyRental`.`host` (`hostID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `propertyRental`.`propertyListing` (`propertyListingID`, `hostID`, `listingName`, `description`, `pricePerNight`, `street`, `city`, `province`, `country`, `status`) VALUES
(20000001, 10000001, 'Urban Oasis', 'Modern apartment in downtown', 00000150.00, '123 Main St', 'New York', 'NY', 'USA', 'Available'),
(20000002, 10000002, 'Country Retreat', 'Cozy cabin surrounded by nature', 00000090.00, '45 Oak Lane', 'Asheville', 'NC', 'USA', 'Available'),
(20000003, 10000003, 'Luxury Loft', 'Spacious loft with skyline views', 00000300.00, '789 High St', 'Chicago', 'IL', 'USA', 'Available'),
(20000004, 10000004, 'City Central', 'Conveniently located apartment', 00000120.00, '567 Pine St', 'San Francisco', 'CA', 'USA', 'Unavailable'),
(20000005, 10000005, 'Beachside Villa', 'Relaxing stay by the beach', 00000200.00, '321 Ocean Ave', 'Miami', 'FL', 'USA', 'Available');

-- -----------------------------------------------------
-- Table `propertyRental`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`guest` (
  `guestID` DECIMAL(8,0)  NOT NULL,
  `userName` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `description` VARCHAR(90) NULL,
  `joinDate` DATE NOT NULL,
  `email` VARCHAR(25) NULL,
  `phoneNumber` VARCHAR(20) NULL,
  PRIMARY KEY (`guestID`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO `propertyRental`.`guest` (`guestID`, `userName`, `password`, `firstName`, `lastName`, `description`, `joinDate`, `email`, `phoneNumber`) VALUES
(30000001, 'guestUser1', 'guest1234', 'David', 'Wilson', 'Frequent traveler', '2023-01-01', 'david.wilson@example.com', '1231231234'),
(30000002, 'guestUser2', 'guest5678', 'Emily', 'Taylor', 'Adventure seeker', '2023-02-10', 'emily.taylor@example.com', '2342342345'),
(30000003, 'guestUser3', 'guest9101', 'Michael', 'Martinez', 'Business traveler', '2023-03-15', 'michael.m@example.com', '3453453456'),
(30000004, 'guestUser4', 'guest1123', 'Sarah', 'Anderson', 'Family vacationer', '2023-04-20', 'sarah.ad@example.com', '4564564567'),
(30000005, 'guestUser5', 'guest3141', 'Chris', 'Lee', 'Culture enthusiast', '2023-05-25', 'chris.lee@example.com', '5675675678');

-- -----------------------------------------------------
-- Table `propertyRental`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`reservation` (
  `reservationID` DECIMAL(8,0)  NOT NULL,
  `guestID` DECIMAL(8,0)  NOT NULL,
  `hostID` DECIMAL(8,0)  NOT NULL,
  `propertyListingID` DECIMAL(8,0)  NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `totalPrice` DECIMAL(10,2) ZEROFILL NOT NULL,
  `status` ENUM('paid', 'unpaid', 'incomplete') NOT NULL,
  PRIMARY KEY (`reservationID`),
  INDEX `hostID_idx` (`hostID` ASC) VISIBLE,
  INDEX `guestID_idx` (`guestID` ASC) VISIBLE,
  INDEX `fk_reservation_propertyListing1_idx` (`propertyListingID` ASC) VISIBLE,
  CONSTRAINT `hostID00`
    FOREIGN KEY (`hostID`)
    REFERENCES `propertyRental`.`host` (`hostID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guestID00`
    FOREIGN KEY (`guestID`)
    REFERENCES `propertyRental`.`guest` (`guestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_propertyListing100`
    FOREIGN KEY (`propertyListingID`)
    REFERENCES `propertyRental`.`propertyListing` (`propertyListingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`hostRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`hostRating` (
  `reservationID` DECIMAL(8,0)  NOT NULL,
  `review` VARCHAR(250) NULL,
  `rating` DECIMAL(3,2)  NOT NULL,
  INDEX `reservationID_idx` (`reservationID` ASC) VISIBLE,
  PRIMARY KEY (`reservationID`),
  CONSTRAINT `reservationID_host_fk`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`propertyRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`propertyRating` (
  `reservationID` DECIMAL(8,0)  NOT NULL,
  `review` VARCHAR(250) NULL,
  `rating` DECIMAL(3,2)  NOT NULL,
  PRIMARY KEY (`reservationID`),
  CONSTRAINT `reservationID_property_fk`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`guestRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`guestRating` (
  `reservationID` DECIMAL(8,0)  NOT NULL,
  `review` VARCHAR(250) NULL,
  `rating` DECIMAL(3,2)  NOT NULL,
  INDEX `reservationID_idx` (`reservationID` ASC) VISIBLE,
  PRIMARY KEY (`reservationID`),
  CONSTRAINT `reservationID_guest_fk`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`transaction` (
  `transactionID` DECIMAL(8,0)  NOT NULL,
  `reservationID` DECIMAL(8,0)  NOT NULL,
  `amount` DECIMAL(10,2) ZEROFILL  NOT NULL,
  `mode` VARCHAR(50) NOT NULL,
  `date` DATE NOT NULL,
  `type` ENUM("Payment", "Refund") NOT NULL,
  PRIMARY KEY (`transactionID`),
  INDEX `fk_transaction_reservation1_idx` (`reservationID` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_reservation10`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
