-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 01:41:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema propertyRental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema propertyRental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `propertyRental` DEFAULT CHARACTER SET utf8 ;
USE `propertyRental` ;

-- -----------------------------------------------------
-- Table `propertyRental`.`host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`host` (
  `hostID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `userName` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `description` VARCHAR(90) NULL,
  `joinDate` DATE NOT NULL,
  `email` VARCHAR(25) NULL,
  `phoneNumber` VARCHAR(20) NULL,
  `earnings` DECIMAL(10,2) ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`hostID`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`propertyListing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`propertyListing` (
  `propertyListingID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `hostID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `listingName` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NULL,
  `pricePerNight` DECIMAL(10,2) UNSIGNED ZEROFILL NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`propertyListingID`),
  INDEX `hostID_idx` (`hostID` ASC) VISIBLE,
  CONSTRAINT `hostID_property_fk`
    FOREIGN KEY (`hostID`)
    REFERENCES `propertyRental`.`host` (`hostID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`guest` (
  `guestID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `userName` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `description` VARCHAR(90) NULL,
  `joinDate` DATE NOT NULL,
  `email` VARCHAR(25) NULL,
  `phoneNumber` VARCHAR(20) NULL,
  PRIMARY KEY (`guestID`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`reservation` (
  `reservationID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `guestID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `hostID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `propertyListingID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `totalPrice` DECIMAL(10,2) ZEROFILL NOT NULL,
  `status` ENUM('paid', 'unpaid', 'incomplete') NOT NULL,
  PRIMARY KEY (`reservationID`),
  INDEX `hostID_idx` (`hostID` ASC) VISIBLE,
  INDEX `guestID_idx` (`guestID` ASC) VISIBLE,
  INDEX `fk_reservation_propertyListing1_idx` (`propertyListingID` ASC) VISIBLE,
  CONSTRAINT `hostID00`
    FOREIGN KEY (`hostID`)
    REFERENCES `propertyRental`.`host` (`hostID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guestID00`
    FOREIGN KEY (`guestID`)
    REFERENCES `propertyRental`.`guest` (`guestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_propertyListing100`
    FOREIGN KEY (`propertyListingID`)
    REFERENCES `propertyRental`.`propertyListing` (`propertyListingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`hostRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`hostRating` (
  `reservationID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `review` VARCHAR(250) NULL,
  `rating` DECIMAL(3,2) UNSIGNED NOT NULL,
  INDEX `reservationID_idx` (`reservationID` ASC) VISIBLE,
  PRIMARY KEY (`reservationID`),
  CONSTRAINT `reservationID_host_fk`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`propertyRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`propertyRating` (
  `reservationID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `review` VARCHAR(250) NULL,
  `rating` DECIMAL(3,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`reservationID`),
  CONSTRAINT `reservationID_property_fk`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`guestRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`guestRating` (
  `reservationID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `review` VARCHAR(250) NULL,
  `rating` DECIMAL(3,2) UNSIGNED NOT NULL,
  INDEX `reservationID_idx` (`reservationID` ASC) VISIBLE,
  PRIMARY KEY (`reservationID`),
  CONSTRAINT `reservationID_guest_fk`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertyRental`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertyRental`.`transaction` (
  `transactionID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `reservationID` DECIMAL(8,0) UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) ZEROFILL UNSIGNED NOT NULL,
  `mode` VARCHAR(50) NOT NULL,
  `date` DATE NOT NULL,
  `type` ENUM("Payment", "Refund") NOT NULL,
  PRIMARY KEY (`transactionID`),
  INDEX `fk_transaction_reservation1_idx` (`reservationID` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_reservation10`
    FOREIGN KEY (`reservationID`)
    REFERENCES `propertyRental`.`reservation` (`reservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
